spring.application.name=example

spring.datasource.url=jdbc:postgresql://localhost:5432/documentation-editing-platform
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


# --- Hikari Connection Pool Settings ---
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# --- JPA / Hibernate Configuration ---
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
# Set dialect explicitly if necessary, though Spring Boot usually detects it
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JDBC Lob Non-contextual Creation ---
spring.jpa.properties.jdbc.lob.non_contextual_creation=true

# spring.port=8081

# Define a custom key using a placeholder
#jwt.secret="f714148fceb0fc13493f32e84a221a5070f4321e3900c11a42c4e8ebda53aea0"

